language: php

php:
  - 5.6

addons:
  code_climate:
    repo_token:
      secure: "pfGGZp/Og6B1Ayu9NmLebl5/dA1WBTPac27PsjiKykW/Y5sVKq2raXMJQwuyyNgvga8tJWvVo2aI6JWOCe9ZbnF07Wb8OU+CVawUsyfo87eFEC8eig9nanshq1fScCwZgdSOsUz5Ys9VTTkcYqfIifhhizX+37EXpmu1xRKbpO32cs+UZ4UFxGv0gg11gW/UaAcosx7BlkDA8hzW+Wbq/opEeceBXyTWxL3iT6Z8KmZgomEm+ZnWmjM56ff/+nind/kvwOGTPTdSos63oU8vw87rrPdERXBCCiI9/1M/f2tRPQIjfFUo8KnNoxY5/aGFtwenvU1vI00jAMTmR+sSK2Ghs6998azpX98YPM6RZDgqu+SPIqoqRUgYZ7j0XSFJ2lnKho42X/LSBWwqsGdXepNlobqTs2xJ2jPD6cCz2BWAK3CkwIXOL4bORCn53SXObS3HoJLwEYJNGm/t7NrdaJ3Y/CpOU2fBeYzzapZXmfqJ6qUbPvGOfnxyTZDNci2JdIJi/woDbukU6lqMY7DrfCdXOK4BJmYpJv3bfecbMyNrpelehoWqofdVGOysZCmY2eOQNmsQMkU2rjUC1a4WRovVAN6XHhLUM7YaisP7b+Hn5qg1RFs61K40m/CVt2MbGbxx79lFR1k29Fsq6e8nh4SXgTq4lt3YKt9cC+vJuoI="

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter
