language: php

php:
  - 5.6

addons:
  code_climate:
    repo_token:
      secure: "BXBI6CaRKDCXeMsaRRJ+CMtoDqJfiJvZ/oB3uR/iBfop9vV15ks1Q0+cGgP159FNFLIthOXnPzx5u5GvH3aKV/6zVWVvlV9VlU4nUL2jKXemNG956cDoLZLjEm9/6SGRyv6Dz5bOJuMIcf9fFP4Est0IQLOCyi8aeMbnJrkU6czPhwWFqMoNB32nMzAsdj6yg+w8VL0D0m18iZtT9QgtAKLtnx5WlulBYhO8C1CbHMhWVZv4/JOQH1VAMcHYA45eh7R2g7jNmm08VRrNF1bG3Jue1f1zPbL3v1L+mYhUOVr62AP/VWChP/HXXuXuQnvURINMErywwaCczx36gepVkYdL5BRhVb+VvQ8FogUPv9uOwC7BjxEL+9F0oaArEMSa9oLWwZLA/go2eLu02TG9+YIPcnPp2HXTeRFyYf1fJxiS7PolNJMLyXruxac6kfrM9xnHw48wSM14ttR4qO9dBTcnFVpmqcgXPUIJ9xE03ap68PRMR+OdSFqsGlvvbkQaU39xagdX4z+8DoEzsVpxGi7seBi6c4gA1b1kpPCpd3n7qhKRjFnTH/mARYV2pi4z6+sNQgdYiyGa8j0LgMty2GeM5SpC1eSZHYN6wLACq5Tm0SmUwgwEbwpsEMRlbj33ov8yZDERHo9VViKcThMhn97zToUHvPGspqfCys5RO70="

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter
